stages:
  - stage: Build
    displayName: 'Build'
    dependsOn: [  ]
    pool:
      vmImage: 'windows-latest'
    jobs:
      - job: Publish
        displayName: 'Publish'
        dependsOn: [  ]
        steps:
          - task: CmdLine@2
            displayName: 'Nuke'
            inputs:
              script: './build.cmd Publish'
          - task: PublishBuildArtifacts@1
            displayName: 'Publish: drop'
            inputs:
              artifactName: drop
              pathToPublish: 'build/output/drop'
          - task: PublishTestResults@2
            condition: succeededOrFailed()
            inputs:
              testResultsFormat: 'VSTest'
              testResultsFiles: $(System.DefaultWorkingDirectory)/build/output/trx/*.trx
          - task: PublishCodeCoverageResults@2
            condition: succeededOrFailed()
            inputs:
              codeCoverageTool: 'Cobertura'
              summaryFileLocation: $(System.DefaultWorkingDirectory)/build/output/cob/Cobertura.xml
