// ReSharper disable StringLiteralTypo
namespace aemarco.Crawler.Model;

public class CountryList
{

    public static string? FindCountry(string text)
    {
        foreach (var entry in Countries)
        {
            var pattern = string.Join('|', entry.Value);
            if (Regex.IsMatch(text, pattern))
            {
                return entry.Key;
            }
        }
        return null;
    }



    private static readonly Dictionary<string, string[]> Countries = new()
    {
        { "Afghanistan", ["Afghanistan", "Afghanistan"] },
        { "Albania", ["Albania", "Albanien"] },
        { "Algeria", ["Algeria", "Algerien"] },
        { "Andorra", ["Andorra", "Andorra"] },
        { "Angola", ["Angola", "Angola"] },
        { "Antigua and Barbuda", ["Antigua and Barbuda", "Antigua und Barbuda"] },
        { "Argentina", ["Argentina", "Argentinien"] },
        { "Armenia", ["Armenia", "Armenien"] },
        { "Australia", ["Australia", "Australien"] },
        { "Austria", ["Austria", "Österreich"] },
        { "Azerbaijan", ["Azerbaijan", "Aserbaidschan"] },
        { "Bahamas", ["Bahamas", "Bahamas"] },
        { "Bahrain", ["Bahrain", "Bahrain"] },
        { "Bangladesh", ["Bangladesh", "Bangladesch"] },
        { "Barbados", ["Barbados", "Barbados"] },
        { "Belarus", ["Belarus", "Weißrussland"] },
        { "Belgium", ["Belgium", "Belgien"] },
        { "Belize", ["Belize", "Belize"] },
        { "Benin", ["Benin", "Benin"] },
        { "Bhutan", ["Bhutan", "Bhutan"] },
        { "Bolivia", ["Bolivia", "Bolivien"] },
        { "Bosnia and Herzegovina", ["Bosnia and Herzegovina", "Bosnien und Herzegowina"] },
        { "Botswana", ["Botswana", "Botswana"] },
        { "Brazil", ["Brazil", "Brasilien"] },
        { "Brunei", ["Brunei", "Brunei"] },
        { "Bulgaria", ["Bulgaria", "Bulgarien"] },
        { "Burkina Faso", ["Burkina Faso", "Burkina Faso"] },
        { "Burundi", ["Burundi", "Burundi"] },
        { "Cabo Verde", ["Cabo Verde", "Cabo Verde"] },
        { "Cambodia", ["Cambodia", "Kambodscha"] },
        { "Cameroon", ["Cameroon", "Kamerun"] },
        { "Canada", ["Canada", "Kanada"] },
        { "Central African Republic", ["Central African Republic", "Zentralafrikanische Republik"] },
        { "Chad", ["Chad", "Tschad"] },
        { "Chile", ["Chile", "Chile"] },
        { "China", ["China", "China"] },
        { "Colombia", ["Colombia", "Kolumbien"] },
        { "Comoros", ["Comoros", "Komoren"] },
        { "Congo, Democratic Republic of the", ["Congo, Democratic Republic of the", "Kongo, Demokratische Republik"] },
        { "Costa Rica", ["Costa Rica", "Costa Rica"] },
        { "Croatia", ["Croatia", "Kroatien"] },
        { "Cuba", ["Cuba", "Kuba"] },
        { "Cyprus", ["Cyprus", "Zypern"] },
        { "Czech Republic", ["Czech Republic", "Tschechische Republik"] },
        { "Denmark", ["Denmark", "Dänemark"] },
        { "Djibouti", ["Djibouti", "Dschibuti"] },
        { "Dominica", ["Dominica", "Dominica"] },
        { "Dominican Republic", ["Dominican Republic", "Dominikanische Republik"] },
        { "East Timor", ["East Timor", "Osttimor"] },
        { "Ecuador", ["Ecuador", "Ecuador"] },
        { "Egypt", ["Egypt", "Ägypten"] },
        { "El Salvador", ["El Salvador", "El Salvador"] },
        { "Equatorial Guinea", ["Equatorial Guinea", "Äquatorialguinea"] },
        { "Eritrea", ["Eritrea", "Eritrea"] },
        { "Estonia", ["Estonia", "Estland"] },
        { "Eswatini", ["Eswatini", "Eswatini"] },
        { "Ethiopia", ["Ethiopia", "Äthiopien"] },
        { "Fiji", ["Fiji", "Fidschi"] },
        { "Finland", ["Finland", "Finnland"] },
        { "France", ["France", "Frankreich"] },
        { "Gabon", ["Gabon", "Gabun"] },
        { "Gambia", ["Gambia", "Gambia"] },
        { "Georgia", ["Georgia", "Georgien"] },
        { "Germany", ["Germany", "Deutschland"] },
        { "Ghana", ["Ghana", "Ghana"] },
        { "Greece", ["Greece", "Griechenland"] },
        { "Grenada", ["Grenada", "Grenada"] },
        { "Guatemala", ["Guatemala", "Guatemala"] },
        { "Guinea", ["Guinea", "Guinea"] },
        { "Guinea-Bissau", ["Guinea-Bissau", "Guinea-Bissau"] },
        { "Guyana", ["Guyana", "Guyana"] },
        { "Haiti", ["Haiti", "Haiti"] },
        { "Honduras", ["Honduras", "Honduras"] },
        { "Hungary", ["Hungary", "Ungarn"] },
        { "Iceland", ["Iceland", "Island"] },
        { "India", ["India", "Indien"] },
        { "Indonesia", ["Indonesia", "Indonesien"] },
        { "Iran", ["Iran", "Iran"] },
        { "Iraq", ["Iraq", "Irak"] },
        { "Ireland", ["Ireland", "Irland"] },
        { "Israel", ["Israel", "Israel"] },
        { "Italy", ["Italy", "Italien"] },
        { "Jamaica", ["Jamaica", "Jamaika"] },
        { "Japan", ["Japan", "Japan"] },
        { "Jordan", ["Jordan", "Jordanien"] },
        { "Kazakhstan", ["Kazakhstan", "Kasachstan"] },
        { "Kenya", ["Kenya", "Kenia"] },
        { "Kiribati", ["Kiribati", "Kiribati"] },
        { "Korea, North", ["Korea, North", "Nordkorea"] },
        { "Korea, South", ["Korea, South", "Südkorea"] },
        { "Kosovo", ["Kosovo", "Kosovo"] },
        { "Kuwait", ["Kuwait", "Kuwait"] },
        { "Kyrgyzstan", ["Kyrgyzstan", "Kirgisistan"] },
        { "Laos", ["Laos", "Laos"] },
        { "Latvia", ["Latvia", "Lettland"] },
        { "Lebanon", ["Lebanon", "Libanon"] },
        { "Lesotho", ["Lesotho", "Lesotho"] },
        { "Liberia", ["Liberia", "Liberia"] },
        { "Libya", ["Libya", "Libyen"] },
        { "Liechtenstein", ["Liechtenstein", "Liechtenstein"] },
        { "Lithuania", ["Lithuania", "Litauen"] },
        { "Luxembourg", ["Luxembourg", "Luxemburg"] },
        { "Madagascar", ["Madagascar", "Madagaskar"] },
        { "Malawi", ["Malawi", "Malawi"] },
        { "Malaysia", ["Malaysia", "Malaysia"] },
        { "Maldives", ["Maldives", "Malediven"] },
        { "Mali", ["Mali", "Mali"] },
        { "Malta", ["Malta", "Malta"] },
        { "Marshall Islands", ["Marshall Islands", "Marshallinseln"] },
        { "Mauritania", ["Mauritania", "Mauretanien"] },
        { "Mauritius", ["Mauritius", "Mauritius"] },
        { "Mexico", ["Mexico", "Mexiko"] },
        { "Micronesia", ["Micronesia", "Mikronesien"] },
        { "Moldova", ["Moldova", "Moldawien"] },
        { "Monaco", ["Monaco", "Monaco"] },
        { "Mongolia", ["Mongolia", "Mongolei"] },
        { "Montenegro", ["Montenegro", "Montenegro"] },
        { "Morocco", ["Morocco", "Marokko"] },
        { "Mozambique", ["Mozambique", "Mosambik"] },
        { "Myanmar", ["Myanmar", "Myanmar"] },
        { "Namibia", ["Namibia", "Namibia"] },
        { "Nauru", ["Nauru", "Nauru"] },
        { "Nepal", ["Nepal", "Nepal"] },
        { "Netherlands", ["Netherlands", "Niederlande"] },
        { "New Zealand", ["New Zealand", "Neuseeland"] },
        { "Nicaragua", ["Nicaragua", "Nicaragua"] },
        { "Niger", ["Niger", "Niger"] },
        { "Nigeria", ["Nigeria", "Nigeria"] },
        { "North Macedonia", ["North Macedonia", "Nordmazedonien"] },
        { "Norway", ["Norway", "Norwegen"] },
        { "Oman", ["Oman", "Oman"] },
        { "Pakistan", ["Pakistan", "Pakistan"] },
        { "Palau", ["Palau", "Palau"] },
        { "Palestine", ["Palestine", "Palästina"] },
        { "Panama", ["Panama", "Panama"] },
        { "Papua New Guinea", ["Papua New Guinea", "Papua-Neuguinea"] },
        { "Paraguay", ["Paraguay", "Paraguay"] },
        { "Peru", ["Peru", "Peru"] },
        { "Philippines", ["Philippines", "Philippinen"] },
        { "Poland", ["Poland", "Polen"] },
        { "Portugal", ["Portugal", "Portugal"] },
        { "Qatar", ["Qatar", "Katar"] },
        { "Romania", ["Romania", "Rumänien"] },
        { "Russia", ["Russia", "Russland", "Russian Federation", "Russian"] },
        { "Rwanda", ["Rwanda", "Ruanda"] },
        { "Saint Kitts and Nevis", ["Saint Kitts and Nevis", "St. Kitts und Nevis"] },
        { "Saint Lucia", ["Saint Lucia", "St. Lucia"] },
        { "Saint Vincent and the Grenadines", ["Saint Vincent and the Grenadines", "St. Vincent und die Grenadinen"] },
        { "Samoa", ["Samoa", "Samoa"] },
        { "San Marino", ["San Marino", "San Marino"] },
        { "Sao Tome and Principe", ["Sao Tome and Principe", "São Tomé und Príncipe"] },
        { "Saudi Arabia", ["Saudi Arabia", "Saudi-Arabien"] },
        { "Senegal", ["Senegal", "Senegal"] },
        { "Serbia", ["Serbia", "Serbien"] },
        { "Seychelles", ["Seychelles", "Seychellen"] },
        { "Sierra Leone", ["Sierra Leone", "Sierra Leone"] },
        { "Singapore", ["Singapore", "Singapur"] },
        { "Slovakia", ["Slovakia", "Slowakei"] },
        { "Slovenia", ["Slovenia", "Slowenien"] },
        { "Solomon Islands", ["Solomon Islands", "Salomonen"] },
        { "Somalia", ["Somalia", "Somalia"] },
        { "South Africa", ["South Africa", "Südafrika"] },
        { "South Sudan", ["South Sudan", "Südsudan"] },
        { "Spain", ["Spain", "Spanien"] },
        { "Sri Lanka", ["Sri Lanka", "Sri Lanka"] },
        { "Sudan", ["Sudan", "Sudan"] },
        { "Suriname", ["Suriname", "Suriname"] },
        { "Sweden", ["Sweden", "Schweden"] },
        { "Switzerland", ["Switzerland", "Schweiz"] },
        { "Syria", ["Syria", "Syrien"] },
        { "Taiwan", ["Taiwan", "Taiwan"] },
        { "Tajikistan", ["Tajikistan", "Tadschikistan"] },
        { "Tanzania", ["Tanzania", "Tansania"] },
        { "Thailand", ["Thailand", "Thailand"] },
        { "Togo", ["Togo", "Togo"] },
        { "Tonga", ["Tonga", "Tonga"] },
        { "Trinidad and Tobago", ["Trinidad and Tobago", "Trinidad und Tobago"] },
        { "Tunisia", ["Tunisia", "Tunesien"] },
        { "Turkey", ["Turkey", "Türkei"] },
        { "Turkmenistan", ["Turkmenistan", "Turkmenistan"] },
        { "Tuvalu", ["Tuvalu", "Tuvalu"] },
        { "Uganda", ["Uganda", "Uganda"] },
        { "Ukraine", ["Ukraine", "Ukraine"] },
        { "United Arab Emirates", ["United Arab Emirates", "Vereinigte Arabische Emirate", "UAE"] },
        { "United Kingdom", ["United Kingdom", "Vereinigtes Königreich", "UK", "GB"] },
        { "United States", ["United States", "Vereinigte Staaten", "USA", "US"] },
        { "Uruguay", ["Uruguay", "Uruguay"] },
        { "Uzbekistan", ["Uzbekistan", "Usbekistan"] },
        { "Vanuatu", ["Vanuatu", "Vanuatu"] },
        { "Vatican City", ["Vatican City", "Vatikanstadt"] },
        { "Venezuela", ["Venezuela", "Venezuela"] },
        { "Vietnam", ["Vietnam", "Vietnam"] },
        { "Yemen", ["Yemen", "Jemen"] },
        { "Zambia", ["Zambia", "Sambia"] },
        { "Zimbabwe", ["Zimbabwe", "Simbabwe"] }
    };
}
